### ISSUE TITLE
Comply with the JSON API spec

### ISSUE THREAD

**Issue by belohlavek** [SPApawa/sistema-trabajos#4]
http://jsonapi.org/

### To-do

- [ ] Only accept JSON requests (except for file upload related resources)
- [ ] All responses must comply with [the provided schema](https://github.com/json-api/json-api/blob/gh-pages/schema)
- [ ] Document API accordingly

**Comment by belohlavek** [comment]
Some progress is being achieved using transformers.

**Comment by belohlavek** [comment]
Hacer los transformers para todos los modelos (al menos un transformer)
Armar controladores para todos los modelos 
Armar servicios para todos los modelos (al menos un servicio)
Comprobar que funcione y cumpla con el spec (postman, no hace falta que los errores cumplan con el spec)

**Comment by belohlavek** [comment]
Closing and replacing with more specific issues.
